'use client';

import React from 'react';
import { useParams, useRouter } from 'next/navigation';
import { useQuery } from '@tanstack/react-query';
import Layout from '@/components/Layout';
import {
  Box,
  Card,
  Typography,
  CircularProgress,
  Button,
  Avatar,
  Divider
} from '@mui/material';
import { ArrowBack as ArrowBackIcon, AutoAwesome as AutoAwesomeIcon } from '@mui/icons-material';
import ReactMarkdown from 'react-markdown';

export default function TalentProfilePage() {
  const params = useParams();
  const router = useRouter();
  const userId = params.id as string;

  const { data, isLoading, isError } = useQuery({
    queryKey: ['talentProfile', userId],
    queryFn: async () => {
      const res = await fetch(`/api/talent/${userId}/profile`);
      if (!res.ok) throw new Error('Failed to generate profile');
      return res.json();
    },
    // Don't refetch on window focus since this calls an AI endpoint
    refetchOnWindowFocus: false,
    staleTime: Infinity
  });

  return (
    <Layout>
      <Box sx={{ maxWidth: 900, mx: 'auto', width: '100%' }}>
        <Button 
          startIcon={<ArrowBackIcon />} 
          onClick={() => router.back()}
          sx={{ mb: 3 }}
        >
          Back to Talent Discovery
        </Button>

        <Card sx={{ p: 4, borderRadius: 3, position: 'relative', overflow: 'visible' }}>
          {/* Decorative AI Glow */}
          <Box sx={{
            position: 'absolute',
            top: -20,
            right: -20,
            width: 100,
            height: 100,
            background: 'radial-gradient(circle, rgba(99,102,241,0.2) 0%, rgba(255,255,255,0) 70%)',
            zIndex: 0
          }} />

          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2, mb: 4, position: 'relative', zIndex: 1 }}>
            <Avatar sx={{ bgcolor: 'primary.main', width: 56, height: 56 }}>
              <AutoAwesomeIcon />
            </Avatar>
            <Box>
              <Typography variant="h5" sx={{ fontWeight: 800 }}>
                AI Talent Profiling Report
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Generated by Groq & LLaMA 3 based on learning history and GitHub code reviews
              </Typography>
            </Box>
          </Box>

          <Divider sx={{ mb: 4 }} />

          {isLoading ? (
            <Box sx={{ display: 'flex', flexDirection: 'column', alignItems: 'center', py: 8 }}>
              <CircularProgress size={48} sx={{ mb: 3 }} />
              <Typography variant="body1" color="text.secondary" sx={{ fontStyle: 'italic' }}>
                Analyzing learning paths and code quality...
              </Typography>
            </Box>
          ) : isError ? (
            <Box sx={{ py: 4, textAlign: 'center' }}>
              <Typography color="error">
                Failed to generate the AI profile. Please ensure the user has data or try again later.
              </Typography>
            </Box>
          ) : (
            <Box sx={{ 
              position: 'relative', 
              zIndex: 1,
              '& h1': { fontSize: '1.75rem', fontWeight: 800, mt: 0, mb: 2, color: 'primary.main' },
              '& h2': { fontSize: '1.25rem', fontWeight: 700, mt: 4, mb: 2, pb: 1, borderBottom: '1px solid', borderColor: 'divider' },
              '& ul': { pl: 3, mb: 3 },
              '& li': { mb: 1, lineHeight: 1.6 },
              '& p': { lineHeight: 1.6, mb: 2, color: 'text.primary' }
            }}>
              <ReactMarkdown>
                {data?.profileMarkdown || '*No report generated.*'}
              </ReactMarkdown>
            </Box>
          )}
        </Card>
      </Box>
    </Layout>
  );
}
